# Scales

ListScales = []
ListScales.append({"Scale": 'Ahava Raba', "H_Steps": 'R, H, 1.5, H, W, H, W, W', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', 'b7']}),
ListScales.append({"Scale": 'Algerian',  "H_Steps": 'R, W, H, W, H, H, H, 1.5, H', "L_Steps": ['1', '2', 'b3', '4', 'b5', 'bb6', 'bbb7']})
ListScales.append({"Scale": 'Altered',  "H_Steps": 'R, H, W, H, W, W, W, W', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Arabian (a)',  "H_Steps": 'R, W, H, W, H, W, H, W, H', "L_Steps": ['1', '2', 'b3', '4', 'b5', 'b6', 'bb7']})
ListScales.append({"Scale": 'Arabian (b)',  "H_Steps": 'R, W, W, H, H, W, W, W', "L_Steps": ['1', '2', '3', '4', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Augmented',  "H_Steps": 'R, 1.5, H, W, W, 1.5, H', "L_Steps": ['1', '#2', '3', '#4', '#5', '##6']})
ListScales.append({"Scale": 'Auxiliary Diminished',  "H_Steps": 'R, W, H, W, H, W, H, W, H', "L_Steps": ['1', '2', 'b3', '4', 'b5', 'b6', 'bb7']})
ListScales.append({"Scale": 'Auxiliary Diminished Blues',  "H_Steps": 'R, H, W, H, W, H, W, H, W', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'bb6', 'bb7']})
ListScales.append({"Scale": 'Balinese',  "H_Steps": 'R, H, W, 2, 1.5, W', "L_Steps": ['1', 'b2', 'b3', '##4', '###5']})
ListScales.append({"Scale": 'Bebop Dominant',  "H_Steps": 'R, W, W, H, W, W, H, H, H', "L_Steps": ['1', '2', '3', '4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Bebop Dominant',  "H_Steps": 'R, W, W, H, W, W, H, H, H', "L_Steps": ['1', '2', '3', '4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Bebop Half Diminished',  "H_Steps": 'R, H, W, W, H, H, H, 1.5, H', "L_Steps": ['1', 'b2', 'b3', '4', 'b5', 'bb6', 'bbb7']})
ListScales.append({"Scale": 'Bebop Major',  "H_Steps": 'R, W, W, H, W, H, H, W, H', "L_Steps": ['1', '2', '3', '4', '5', 'b6', 'bb7']})
ListScales.append({"Scale": 'Bebop Minor',  "H_Steps": 'R, W, H, H, H, W, W, H, W', "L_Steps": ['1', '2', 'b3', '3', 'bb5', 'bb6', 'bb7']})
ListScales.append({"Scale": 'Blues',  "H_Steps": 'R, 1.5, W, H, H, 1.5, W', "L_Steps": ['1', '#2', '#3', '#4', '5', '#6']})
ListScales.append({"Scale": 'Blues Variation 1',  "H_Steps": 'R, 1.5, W, H, H, 1.5, H, H', "L_Steps": ['1', '#2', '#3', '#4', '5', '#6', '7']})
ListScales.append({"Scale": 'Blues Variation 2',  "H_Steps": 'R, 1.5, H, H, H, H, 1.5, H, H', "L_Steps": ['1', '#2', '3', '4', 'b5', 'bb6', 'b7']})
ListScales.append({"Scale": 'Blues Variation 3',  "H_Steps": 'R, 1.5, H, H, H, H, W, H, HH', "L_Steps": ['1', '#2', '3', '4', 'b5', 'bb6', 'bb7']})
ListScales.append({"Scale": 'Byzantine',  "H_Steps": 'R, H, 1.5, H, W, H, 1.5, H', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Chinese',  "H_Steps": 'R, 2, W, H, 2, H', "L_Steps": ['1', '##2', '##3', '##4', '4x#5']})
ListScales.append({"Scale": 'Chinese 2',  "H_Steps": 'R, W, 1.5, W, W, 1.5', "L_Steps": ['1', '2', '#3', '##4', '##5']})
ListScales.append({"Scale": 'Chinese Mongolian',  "H_Steps": 'R, W, W, 1.5, W, 1.5', "L_Steps": ['1', '2', '3', '##4', '##5']})
ListScales.append({"Scale": 'Diatonic',  "H_Steps": 'R, W, W, 1.5, W, 1.5', "L_Steps": ['1', '2', '3', '##4', '##5']})
ListScales.append({"Scale": 'Diminished',  "H_Steps": 'R, W, H, W, H, W, H, W, H', "L_Steps": ['1', '2', 'b3', '4', 'b5', 'b6', 'bb7']})
ListScales.append({"Scale": 'Diminished, Half',  "H_Steps": 'R, H, W, H, W, H, H, W, W', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'bb6', 'bbb7']})
ListScales.append({"Scale": 'Diminished, Whole Tone',  "H_Steps": 'R, H, W, H, W, W, W, W', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Dominant 7th',  "H_Steps": 'R, W, W, H, W, W, H, W', "L_Steps": ['1', '2', '3', '4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Dominant Pentatonic',  "H_Steps": 'R, W, W, 1.5, 1.5, W', "L_Steps": ['1', '2', '3', '##4', '###5']})
ListScales.append({"Scale": 'Dorian',  "H_Steps": 'R, W, H, W, W, W, H, W', "L_Steps": ['1', '2', 'b3', '4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Dorian #4',  "H_Steps": 'R, W, H, 1.5, H, W, H, W', "L_Steps": ['1', '2', 'b3', '#4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Double Harmonic',  "H_Steps": 'R, H, 1.5, H, W, H, 1.5, H', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Egyptian',  "H_Steps": 'R, W, 1.5, W, W, 1.5', "L_Steps": ['1', '2', '#3', '##4', '##5']})
ListScales.append({"Scale": 'Eight Tone Spanish',  "H_Steps": 'R, H, W, H, H, H, W, W, W', "L_Steps": ['1', 'b2', 'b3', '3', 'bb5', 'bbb6', 'bbb7']})
ListScales.append({"Scale": 'Enigmatic',  "H_Steps": 'R, H, 1.5, W, W, W, H, H', "L_Steps": ['1', 'b2', '3', '#4', '#5', '#6', '7']})
ListScales.append({"Scale": 'Ethiopian (A raray)',  "H_Steps": 'R, W, W, H, W, W, W, H', "L_Steps": ['1', '2', '3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Ethiopian (Geez & Ezel)',  "H_Steps": 'R, W, H, W, W, H, W, W', "L_Steps": ['1', '2', 'b3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Half Diminished #2 (Locrian)',  "H_Steps": 'R, H, W, W, H, W, W, W', "L_Steps": ['1', 'b2', 'b3', '4', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Harmonic Minor',  "H_Steps": 'R, W, H, W, W, H, 1.5, H', "L_Steps": ['1', '2', 'b3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Hawaiian',  "H_Steps": 'R, W, H, W, W, W, W, H', "L_Steps": ['1', '2', 'b3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Hindu',  "H_Steps": 'R, W, W, H, W, H, W, W', "L_Steps": ['1', '2', '3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Hindustan',  "H_Steps": 'R, W, W, H, W, H, W, W', "L_Steps": ['1', '2', '3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Hirajoshi',  "H_Steps": 'R, W, H, 2, H, 2', "L_Steps": ['1', '2', 'b3', '##4', '#5']})
ListScales.append({"Scale": 'Hirajoshi 2',  "H_Steps": 'R, 2, H, 2, W, H', "L_Steps": ['1', '##2', '#3', '4x#4', '4x#5']})
ListScales.append({"Scale": 'Hungarian Gypsy Persian',  "H_Steps": 'R, H, 1.5, H, W, H, 1.5, H', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Hungarian Major',  "H_Steps": 'R, 1.5, H, W, H, W, H, W', "L_Steps": ['1', '#2', '3', '#4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Ionian',  "H_Steps": 'R, W, W, H, W, W, W, H', "L_Steps": ['1', '2', '3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Ionian #5',  "H_Steps": 'R, W, W, H, 1.5, H, W, H', "L_Steps": ['1', '2', '3', '4', '#5', '6', '7']})
ListScales.append({"Scale": 'Iwato',  "H_Steps": 'R, H, 2, H, 2, W', "L_Steps": ['1', 'b2', '#3', '#4', '###5']})
ListScales.append({"Scale": 'Japanese (A)',  "H_Steps": 'R, H, 2, W, H, 2', "L_Steps": ['1', 'b2', '#3', '##4', '#5']})
ListScales.append({"Scale": 'Japanese (B)',  "H_Steps": 'R, W, 1.5, W, H, 2', "L_Steps": ['1', '2', '#3', '##4', '#5']})
ListScales.append({"Scale": 'Japanese (Ichikosucho)',  "H_Steps": 'R, W, W, W, H, W, W, H', "L_Steps": ['1', '2', '3', '#4', '5', '6', '7']})
ListScales.append({"Scale": 'Japanese (in sen)',  "H_Steps": 'R, H, 2, W, 1.5, W', "L_Steps": ['1', 'b2', '#3', '##4', '###5']})
ListScales.append({"Scale": 'Japanese (Taishikicho)',  "H_Steps": 'R, W, W, H, H, H, W, H, HH', "L_Steps": ['1', '2', '3', '4', 'b5', 'bb6', 'bb7']})
ListScales.append({"Scale": 'Jewish (Adonai Malakh)',  "H_Steps": 'R, H, H, H, W, W, W, H, W', "L_Steps": ['1', 'b2', 'bb3', 'b3', 'bb5', 'bb6', 'bb7']})
ListScales.append({"Scale": 'Jewish (Magen Abot)',  "H_Steps": 'R, H, W, H, W, W, W, H, H', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Kumoi',  "H_Steps": 'R, W, H, 2, W, 1.5', "L_Steps": ['1', '2', 'b3', '##4', '##5']})
ListScales.append({"Scale": 'Kumoi 2',  "H_Steps": 'R, H, 2, W, H, 2', "L_Steps": ['1', 'b2', '#3', '##4', '#5']})
ListScales.append({"Scale": 'Leading Whole Tone',  "H_Steps": 'R, W, W, W, W, W, H, H', "L_Steps": ['1', '2', '3', '#4', '#5', '#6', '7']})
ListScales.append({"Scale": 'Locrian',  "H_Steps": 'R, H, W, W, H, W, W, W', "L_Steps": ['1', 'b2', 'b3', '4', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Locrian 6',  "H_Steps": 'R, H, W, W, H, 1.5, W, H', "L_Steps": ['1', 'b2', 'b3', '4', 'b5', '6', '7']})
ListScales.append({"Scale": 'Lydian',  "H_Steps": 'R, W, W, W, H, W, W, H', "L_Steps": ['1', '2', '3', '#4', '5', '6', '7']})
ListScales.append({"Scale": 'Lydian #2',  "H_Steps": 'R, 1.5, H, W, H, W, W, H', "L_Steps": ['1', '#2', '3', '#4', '5', '6', '7']})
ListScales.append({"Scale": 'Lydian Diminished',  "H_Steps": 'R, W, H, 1.5, H, W, W, H', "L_Steps": ['1', '2', 'b3', '#4', '5', '6', '7']})
ListScales.append({"Scale": 'Lydian Minor',  "H_Steps": 'R, W, W, W, H, H, W, W', "L_Steps": ['1', '2', '3', '#4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Major',  "H_Steps": 'R, W, W, H, W, W, W, H', "L_Steps": ['1', '2', '3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Major Blues',  "H_Steps": 'R, W, H, H, 1.5, W, 1.5', "L_Steps": ['1', '2', 'b3', '3', '5', '6']})
ListScales.append({"Scale": 'Major Locrian',  "H_Steps": 'R, W, W, H, H, W, W, W', "L_Steps": ['1', '2', '3', '4', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Major Pentatonic',  "H_Steps": 'R, W, W, 1.5, W, 1.5', "L_Steps": ['1', '2', '3', '##4', '##5']})
ListScales.append({"Scale": 'Melodic Minor',  "H_Steps": 'R, W, H, W, W, W, W, H', "L_Steps": ['1', '2', 'b3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Minor Pentatonic',  "H_Steps": 'R, 1.5, W, W, 1.5, W', "L_Steps": ['1', '#2', '#3', '##4', '###5']})
ListScales.append({"Scale": 'Mixo-Blues',  "H_Steps": 'R, 1.5, H, H, H, H, 1.5, W', "L_Steps": ['1', '#2', '3', '4', 'b5', 'bb6', 'b7']})
ListScales.append({"Scale": 'Mixolydian',  "H_Steps": 'R, W, W, H, W, W, H, W', "L_Steps": ['1', '2', '3', '4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Mohammedan',  "H_Steps": 'R, W, H, W, W, H, 1.5, H', "L_Steps": ['1', '2', 'b3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Moorish Phrygian',  "H_Steps": 'R, H, W, H, H, W, H, W, HH', "L_Steps": ['1', 'b2', 'b3', '3', 'bb5', 'bb6', 'bbb7']})
ListScales.append({"Scale": 'Natural Minor',  "H_Steps": 'R, W, H, W, W, H, W, W', "L_Steps": ['1', '2', 'b3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Natural Pure Minor',  "H_Steps": 'R, W, H, W, W, H, W, W', "L_Steps": ['1', '2', 'b3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Neopolitan',  "H_Steps": 'R, H, W, W, W, H, 1.5, H', "L_Steps": ['1', 'b2', 'b3', '4', '5', 'b6', '7']})
ListScales.append({"Scale": 'Neopolitan Major',  "H_Steps": 'R, H, W, W, W, W, W, H', "L_Steps": ['1', 'b2', 'b3', '4', '5', '6', '7']})
ListScales.append({"Scale": 'Nine Tone',  "H_Steps": 'R, W, H, H, W, H, H, H, W, H', "L_Steps": ['1', '2', 'b3', '3', 'b5', 'bb6', 'bbb7']})
ListScales.append({"Scale": 'Oriental (a)',  "H_Steps": 'R, H, 1.5, H, H, W, W, W', "L_Steps": ['1', 'b2', '3', '4', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Overtone',  "H_Steps": 'R, W, W, W, H, W, H, W', "L_Steps": ['1', '2', '3', '#4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Overtone Dominant',  "H_Steps": 'R, W, W, W, H, W, H, W', "L_Steps": ['1', '2', '3', '#4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Pelog 2',  "H_Steps": 'R, H, W, 2, 1.5, W', "L_Steps": ['1', 'b2', 'b3', '##4', '###5']})
ListScales.append({"Scale": 'Pelong',  "H_Steps": 'R, H, W, 2, H, 2', "L_Steps": ['1', 'b2', 'b3', '##4', '#5']})
ListScales.append({"Scale": 'Pentatonic Blues',  "H_Steps": 'R, 1.5, W, H, H, 1.5, W', "L_Steps": ['1', '#2', '#3', '#4', '5', '#6']})
ListScales.append({"Scale": 'Pentatonic Neutral',  "H_Steps": 'R, W, 1.5, W, 1.5, W', "L_Steps": ['1', '2', '#3', '##4', '###5']})
ListScales.append({"Scale": 'Persian',  "H_Steps": 'R, H, 1.5, H, H, W, 1.5, H', "L_Steps": ['1', 'b2', '3', '4', 'b5', 'b6', '7']})
ListScales.append({"Scale": 'Phrygian',  "H_Steps": 'R, H, W, W, W, H, W, W', "L_Steps": ['1', 'b2', 'b3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Phrygian Major',  "H_Steps": 'R, H, 1.5, H, W, H, W, W', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Prometheus',  "H_Steps": 'R, W, W, W, 1.5, H, W', "L_Steps": ['1', '2', '3', '#4', '##5', '#6']})
ListScales.append({"Scale": 'Prometheus Neopolitan',  "H_Steps": 'R, H, 1.5, W, 1.5, H, W', "L_Steps": ['1', 'b2', '3', '#4', '##5', '#6']})
ListScales.append({"Scale": 'Roumanian Minor',  "H_Steps": 'R, W, H, 1.5, H, W, H, W', "L_Steps": ['1', '2', 'b3', '#4', '5', '6', 'b7']})
ListScales.append({"Scale": 'Six Tone Symmetrical',  "H_Steps": 'R, H, 1.5, H, 1.5, H, 1.5', "L_Steps": ['1', 'b2', '3', '4', '#5', '6']})
ListScales.append({"Scale": 'Spanish Gypsy',  "H_Steps": 'R, H, 1.5, H, W, H, W, W', "L_Steps": ['1', 'b2', '3', '4', '5', 'b6', 'b7']})
ListScales.append({"Scale": 'Super Locrian',  "H_Steps": 'R, H, W, H, W, W, W, W', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'b6', 'b7']})
ListScales.append({"Scale": 'Ultralocrian',  "H_Steps": 'R, H, W, H, W, W, H, 1.5', "L_Steps": ['1', 'b2', 'b3', '3', 'b5', 'b6', 'bb7']})
ListScales.append({"Scale": 'Whole Tone',  "H_Steps": 'R, W, W, W, W, W, W', "L_Steps": ['1', '2', '3', '#4', '#5', '#6']})
ListScales.append({"Scale": 'All',  "H_Steps": 'R, H, H, H, H, H, H, H, H, H, H, H, H', "L_Steps": ['1', 'b2', '2', 'b3', '3', '4', 'b5', '5', 'b6', '6', 'b7', '7']})

#Intervals
ListScales.append({"Scale": 'Perfect Unison', "H_Steps": 'R, 0', "L_Steps": ['1']})
ListScales.append({"Scale": 'Minor Second', "H_Steps": 'R, 1', "L_Steps": ['1', 'b2']})
ListScales.append({"Scale": 'Augmented Unison', "H_Steps": 'R, 1', "L_Steps": ['1', 'b2']})
ListScales.append({"Scale": 'Major Second', "H_Steps": 'R, 2', "L_Steps": ['1', '2']})
ListScales.append({"Scale": 'Diminished Third', "H_Steps": 'R, 2', "L_Steps": ['1', '2']})
ListScales.append({"Scale": 'Minor Third', "H_Steps": 'R, 3', "L_Steps": ['1', 'b3']})
ListScales.append({"Scale": 'Augmented Second', "H_Steps": 'R, 3', "L_Steps": ['1', 'b3']})
ListScales.append({"Scale": 'Major Third', "H_Steps": 'R, 4', "L_Steps": ['1', '3']})
ListScales.append({"Scale": 'Diminished Fourth', "H_Steps": 'R, 4', "L_Steps": ['1', '3']})
ListScales.append({"Scale": 'Perfect Fourth', "H_Steps": 'R, 5', "L_Steps": ['1', '4']})
ListScales.append({"Scale": 'Augmented Third', "H_Steps": 'R, 5', "L_Steps": ['1', '4']})
ListScales.append({"Scale": 'Diminished Fifth', "H_Steps": 'R, 6', "L_Steps": ['1', 'b5']})
ListScales.append({"Scale": 'Augmented Fourth', "H_Steps": 'R, 6', "L_Steps": ['1', 'b5']})
ListScales.append({"Scale": 'Perfect Fifth', "H_Steps": 'R, 7', "L_Steps": ['1', '5']})
ListScales.append({"Scale": 'Diminished Sixth', "H_Steps": 'R, 7', "L_Steps": ['1', '5']})
ListScales.append({"Scale": 'Minor Sixth', "H_Steps": 'R, 8', "L_Steps": ['1', 'b6']})
ListScales.append({"Scale": 'Augmented Fifth', "H_Steps": 'R, 8', "L_Steps": ['1', 'b6']})
ListScales.append({"Scale": 'Major Sixth', "H_Steps": 'R, 9', "L_Steps": ['1', '6']})
ListScales.append({"Scale": 'Diminished Seventh', "H_Steps": 'R, 9', "L_Steps": ['1', '6']})
ListScales.append({"Scale": 'Minor Seventh', "H_Steps": 'R, 10', "L_Steps": ['1', 'b7']})
ListScales.append({"Scale": 'Augmented Sixth', "H_Steps": 'R, 10', "L_Steps": ['1', 'b7']})
ListScales.append({"Scale": 'Major Seventh', "H_Steps": 'R, 11', "L_Steps": ['1', '7']})
ListScales.append({"Scale": 'Diminished Octave', "H_Steps": 'R, 11', "L_Steps": ['1', '7']})
ListScales.append({"Scale": 'Perfect Octave', "H_Steps": 'R, 12', "L_Steps": ['1']})
ListScales.append({"Scale": 'Augmented Seventh', "H_Steps": 'R, 12', "L_Steps": ['1']})

ShortList_Scale = {
  'Major', 'Major Blues', 'Blues', 'Major Pentatonic', 'Pentatonic Blues', 'Melodic Minor', 'Natural Minor', 'Diminished', 'Mixolydian', 'Phrygian', 'Locrian', 'Spanish Gypsy'
}
