# Tunings

tuning_dict = {
    'Guitar 7 Standard': ['B', 'E', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 7 Common': ['B', 'C', 'E', 'G', 'C', 'E', 'G'],
    'Guitar 7 Big Guitar': ['G', 'C', 'E', 'G', 'C', 'E', 'G'],
    'Guitar 7 Brazilian': ['C', 'E', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 7 1/3Rd Size': ['F', 'Bb', 'D', 'F', 'Bb', 'D', 'F'],
    'Guitar 7 Russian': ['D', 'G', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 7 Russian Alt 1': ['C', 'G', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 7 Drop A ': ['A', 'E', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 7 Alt 1': ['E', 'A', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 7 Alt 2': ['E', 'G', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 7 Alt 3': ['C', 'G', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 7 Alt 4': ['D', 'G', 'C', 'D', 'G', 'A#', 'D'],
    'Guitar 7 Alt 5': ['B', 'F#', 'B', 'E', 'A', 'D', 'F#'],
    'Guitar 6 Standard': ['E', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 6 Drop D': ['D', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 6 Half Step Down': ['D#', 'G#', 'C#', 'F#', 'A#', 'D#'],
    'Guitar 6 Full Step Down': ['D', 'G', 'C', 'F', 'A', 'D'],
    'Guitar 6 1 and 1/2 Steps Down': ['C#', 'F#', 'B', 'E', 'G#', 'C#'],
    'Guitar 6 Double Drop D': ['D', 'A', 'D', 'G', 'B', 'D'],
    'Guitar 6 Drop C': ['C', 'G', 'C', 'F', 'A', 'D'],
    'Guitar 6 Drop C#': ['C#', 'G#', 'C#', 'F#', 'A#', 'D#'],
    'Guitar 6 Drop B': ['B', 'F#', 'B', 'E', 'G#', 'C#'],
    'Guitar 6 Drop A#': ['A#', 'F', 'A#', 'D#', 'G', 'C'],
    'Guitar 6 Drop A': ['A', 'E', 'A', 'D', 'F#', 'B'],
    'Guitar 6 Open D': ['D', 'A', 'D', 'F#', 'A', 'D'],
    'Guitar 6 Open D Minor': ['D', 'A', 'D', 'F', 'A', 'D'],
    'Guitar 6 Open G': ['D', 'G', 'D', 'G', 'B', 'D'],
    'Guitar 6 Open G Minor': ['D', 'G', 'D', 'G', 'A#', 'D'],
    'Guitar 6 Open C': ['C', 'G', 'C', 'G', 'C', 'E'],
    'Guitar 6 Open C#': ['C#', 'F#', 'B', 'E', 'G#', 'C#'],
    'Guitar 6 Open C Minor': ['C', 'G', 'C', 'G', 'C', 'D#'],
    'Guitar 6 Open E7': ['E', 'G#', 'D', 'E', 'B', 'E'],
    'Guitar 6 Open E Minor7': ['E', 'B', 'D', 'G', 'B', 'E'],
    'Guitar 6 Open G Major7': ['D', 'G', 'D', 'F#', 'B', 'D'],
    'Guitar 6 Open A Minor': ['E', 'A', 'E', 'A', 'C', 'E'],
    'Guitar 6 Open A Minor7': ['E', 'A', 'E', 'G', 'C', 'E'],
    'Guitar 6 Open E': ['E', 'B', 'E', 'G#', 'B', 'E'],
    'Guitar 6 Open A': ['E', 'A', 'C#', 'E', 'A', 'E'],
    'Guitar 6 C Tuning': ['C', 'F', 'A#', 'D#', 'G', 'C'],
    'Guitar 6 C# Tuning': ['C#', 'F#', 'B', 'E', 'G#', 'C#'],
    'Guitar 6 Bb Tuning': ['A#', 'D#', 'G#', 'C#', 'F', 'A#'],
    'Guitar 6 A to A (Baritone)': ['A', 'D', 'G', 'C', 'E', 'A'],
    'Guitar 6 D A D D D D': ['D', 'A', 'D', 'D', 'D', 'D'],
    'Guitar 6 C G D G B D': ['C', 'G', 'D', 'G', 'B', 'D'],
    'Guitar 6 C G D G B E': ['C', 'G', 'D', 'G', 'B', 'E'],
    'Guitar 6 D A D E A D': ['D', 'A', 'D', 'E', 'A', 'D'],
    'Guitar 6 D G D G A D': ['D', 'G', 'D', 'G', 'A', 'D'],
    'Guitar 6 Open Dsus2': ['D', 'A', 'D', 'G', 'A', 'D'],
    'Guitar 6 Open Gsus2': ['D', 'G', 'D', 'G', 'C', 'D'],
    'Guitar 6 G6': ['D', 'G', 'D', 'G', 'B', 'E'],
    'Guitar 6 Modal G': ['D', 'G', 'D', 'G', 'C', 'D'],
    'Guitar 6 Overtone': ['C', 'E', 'G', 'A#', 'C', 'D'],
    'Guitar 6 Pentatonic': ['A', 'C', 'D', 'E', 'G', 'A'],
    'Guitar 6 Minor Third': ['C', 'D#', 'F#', 'A', 'C', 'D#'],
    'Guitar 6 Major Third': ['C', 'E', 'G#', 'C', 'E', 'G#'],
    'Guitar 6 All Fourths': ['E', 'A', 'D', 'G', 'C', 'F'],
    'Guitar 6 Augmented Fourths': ['C', 'F#', 'C', 'F#', 'C', 'F#'],
    'Guitar 6 Slow Motion': ['D', 'G', 'D', 'F', 'C', 'D'],
    'Guitar 6 Admiral': ['C', 'G', 'D', 'G', 'B', 'C'],
    'Guitar 6 Buzzard': ['C', 'F', 'C', 'G', 'A#', 'F'],
    'Guitar 6 Face': ['C', 'G', 'D', 'G', 'A', 'D'],
    'Guitar 6 Four and Twenty': ['D', 'A', 'D', 'D', 'A', 'D'],
    'Guitar 6 Ostrich': ['D', 'D', 'D', 'D', 'D', 'D'],
    'Guitar 6 Capo 200': ['C', 'G', 'D', 'D#', 'D', 'D#'],
    'Guitar 6 Balalaika': ['E', 'A', 'D', 'E', 'E', 'A'],
    'Guitar 6 Cittern One': ['C', 'F', 'C', 'G', 'C', 'D'],
    'Guitar 6 Cittern Two': ['C', 'G', 'C', 'G', 'C', 'G'],
    'Guitar 6 Dobro': ['G', 'B', 'D', 'G', 'B', 'D'],
    'Guitar 6 Lefty': ['E', 'B', 'G', 'D', 'A', 'E'],
    'Guitar 6 Mandoguitar': ['C', 'G', 'D', 'A', 'E', 'B'],
    'Guitar 6 Rusty Cage': ['B', 'A', 'D', 'G', 'B', 'E'],
    'Guitar 5 Charango': ['G', 'C', 'E', 'A', 'E'],
    'Bass 4 Standard': ['E', 'A', 'D', 'G'],
    'Bass 4 Drop D': ['D', 'A', 'D', 'G'],
    'Bass 4 Semitone Flat': ['D#', 'G#', 'C#', 'F#'],
    'Bass 4 Drop D Semitone Flat': ['C#', 'G#', 'C#', 'F#'],
    'Bass 4 Low B': ['B', 'E', 'A', 'D'],
    'Bass 4 Open A': ['E', 'A', 'E', 'A'],
    'Bass 4 Open E': ['E', 'B', 'E', 'G#'],
    'Bass 4 Tenor Tuning': ['A', 'D', 'G', 'C'],
    'Bass 4 Piccolo Bass': ['E', 'A', 'D', 'G'],
    'Bass 4 Drop B': ['B', 'A', 'D', 'G'],
    'Bass 4 Old Skool Standard': ['G', 'C', 'F', 'B'],
    'Bass 5 Standard B': ['B', 'E', 'A', 'D', 'G'],
    'Bass 5 Standard C': ['E', 'A', 'D', 'G', 'C'],
    'Bass 5 Tenor Tuning': ['A', 'D', 'G', 'C', 'F'],
    'Bass 5 F# BEAD': ['F#', 'B', 'E', 'A', 'D'],
    'Bass 5 Drop D': ['A', 'E', 'A', 'D', 'G'],
    'Bass 6 Standard': ['B', 'E', 'A', 'D', 'G', 'C'],
    'Bass 6 E A D G C F': ['E', 'A', 'D', 'G', 'C', 'F'],
    'Bass 6 F# B E A D G': ['F#', 'B', 'E', 'A', 'D', 'G'],
    'Banjo 4 Open G': ['D', 'G', 'B', 'D'],
    'Banjo 4 Dropped C': ['C', 'G', 'B', 'D'],
    'Banjo 4 Open D': ['D', 'F#', 'A', 'D'],
    'Banjo 4 Open Gm': ['D', 'G', 'Bb', 'D'],
    'Banjo 4 Open G Modal': ['D', 'G', 'A', 'D'],
    'Mandolin 4 Standard': ['G', 'D', 'A', 'E'],
    'Mandolin 4 Dropped D': ['G', 'D', 'A', 'D'],
    'Bouzouki 4 Traditional': ['C', 'F', 'A', 'D'],
    'Bouzouki 4 Standard': ['G', 'D', 'A', 'E'],
    'Bouzouki 4 Dropped D': ['G', 'D', 'A', 'D'],
    'Bouzouki 4 Open G6 / Em7': ['D', 'G', 'B', 'E'],
    'Bouzouki 4 Open A5': ['D', 'A', 'D', 'A'],
    'Bouzouki 4 Open F6 / Dm7': ['D', 'A', 'F', 'C'],
    'Ukulele 4 Baritone': ['D', 'G', 'B', 'E'],  # http://www.ukuleletricks.com/ukulele-tuning-how-to-tune-your-ukulele/
    'Ukulele 4 Slack-key': ['G', 'C', 'E', 'G'],
    'Ukulele 4 English Tuning': ['A', 'D', 'F#', 'B'],
    'Ukulele 4 Canadian Tuning': ['A', 'D', 'F#', 'B'],
    'Ukulele 4 Soprano Alt 1': ['G', 'C', 'E', 'A'],  # http://www.get-tuned.com/alternate-ukulele-tunings.php
    'Ukulele 4 Soprano Alt 2': ['A', 'D', 'F#', 'B'],
    'Ukulele 4 Soprano Alt 3': ['G', 'D', 'A', 'E'],
    'Ukulele 4 Concert': ['A', 'D', 'F#', 'B'],
    'Ukulele 4 Tenor': ['G', 'C', 'E', 'A'],
}
